# Generated by Django 4.2.9 on 2024-02-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NewsPaper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlenewsarticle",
            name="publisher",
            field=models.CharField(default="Unknown Publisher", max_length=800),
        ),
    ]
